### ISSUE TITLE
Problem with CS:GO in GamePanelX

### ISSUE THREAD

**Issue by BAILANDO** [devryan/GamePanelX-V3#124]
Hello, i have big problem with csgo start server on GamePanelX onUbuntu 14.04 LTS. When i start CSGO server, then i see error : 

./srcds_run: 32: ./srcds_run: pushd: not found ./srcds_run: 35: ./srcds_run: popd: not found Server will auto-restart if there is a crash. LD_LIBRARY_PATH=/var/www/html/cp/_SERVERS/accounts/csgo/XXXXXXX:27016/740/ bin:/var/www/html/cp/_SERVERS/accounts/csgo/XXXXXXX:27016/740:/var/www/htm l/cp/_SERVERS/accounts/csgo/XXXXXXX:27016/740/bin: Failed to open libtier0.so (libtier0.so: cannot open shared object file: No such file or directory) Add "-debug" to the ./srcds_run command line to generate a debug.log to help wit h solving this problem Tue Aug 4 22:46:27 CEST 2015: Server restart in 10 seconds

Can anyone help me with this please? When i create TF2 server, then this server run without problems. Thanks for help guys, i really need this help.

P.S.: when i start server from command line on terminal then server is running without problem

**Comment by gOOvER** [comment]
I Think GamePanelX is Dead. Since Nov 2014 no commit ;)

Try Easy-WI

https://easy-wi.com/

**Comment by devryan** [comment]
This has been fixed on the ip_port_fix branch.  We need people to test it:

https://github.com/devryan/GamePanelX-V3/tree/ip_port_fix

**Comment by Flegma** [comment]
Still not working. 
I installed ip_port_fix branch but when i try to start the server from panel it does not start.
When i try to start the server from command line, it works.

**Comment by siasur** [comment]
Are you sure that you are testing the correct branch(es)?

If you are just using ``GamePanel X`` you need the branch named "*ip_port_fix*".
If you are using ``GamePanel X Remote`` in addition you'll still need the "*ip_port_fix*" from ``GamePanel X`` and from the ``GamePanel X Remote`` you'll need the "*dev*" branch

**Comment by Flegma** [comment]
Yes i chose 'ip_port_fix' for GamePanel X and the 'dev' branch for GamePanel X Remote.
(https://github.com/devryan/GamePanelX-V3-Remote/tree/dev and https://github.com/devryan/GamePanelX-V3/tree/ip_port_fix)
I did new installation of the "ip_port_fix" and new installation of "dev" for remote. 
Server template is created and servers are created with "ip.port" (instead of ip:port) but when i start them from the panel they are not starting and console is not working, but when i go manually on remote server to the ip.port folder and start the server, its working but its still showing server as offline.

**Comment by devryan** [comment]
Ok, can you "ps -ef | grep srcds" on your server? Sounds like another server is running or your startup parameteres are wrong on your server you are creating.  Check out the startup params in the master control panel that it's going to use, does everything look correct?

I'd be curious to have you join IRC and present your desktop to see this, as I've confirmed my own servers are working great with this fix.  Also, do you have any other control panels running (plesk,cpanel), selinux enabled, etc?  Any httpd plugins for security running?

**Comment by Flegma** [comment]
Its working now. I tested it again.
The problem was that the Remote Server was outdated and CSF was blocking port 27015 (or any other i used) on a Master Server, so the csgo remote server was running but it was not shown in a Master Server's panel.

**Comment by Flegma** [comment]
Another problem - when saving server information like maxplayers and stuff, it reverts rcon_password to just rcon, so the rcon is not working anymore.

**Comment by devryan** [comment]
This has been fixed, see latest commits on master branch of master+remote.  https://github.com/devryan/GamePanelX-V3/commit/29554eb7ed86c81e7fb4a919d4f37ebf5b39c27f
