### ISSUE TITLE
Failed to open libtier0.so

### ISSUE THREAD

**Issue by matamata4** [devryan/GamePanelX-V3#129]
Hello dear git fellows,

I am experiencing the following issue when trying to start a gameserver(Fresh install of gpx and steam on a fresh debian 8.2 installation)

"./srcds_run: 32: ./srcds_run: pushd: not found ./srcds_run: 35: ./srcds_run: popd: not found Server will auto-restart if there is a crash. LD_LIBRARY_PATH=/var/www/html/_SERVERS/accounts/test/5.135.83.95:27016/740/bin:/ var/www/html/_SERVERS/accounts/test/5.135.83.95:27016/740:/var/www/html/_SERVERS /accounts/test/5.135.83.95:27016/740/bin: Failed to open libtier0.so (libtier0.so: cannot open shared object file: No such file or directory) Add "-debug" to the ./srcds_run command line to generate a debug.log to help wit h solving this problem Fri Oct 30 05:58:44 EDT 2015: Server restart in 10 seconds"

I should note that all the corect libs are installed and in the correct folder but for some reason it just won't work.

When checking for the file manually the file is there.

The /var/www/html/_SERVERS/accounts/test/5.135.83.95:27016/740 folder has 655 privileges and it's owned by www-data.

I really need some help, this is driving me crazy ...

Thank you for your time!

**Comment by siasur** [comment]
The Problem is the name of the folder where the servers are located. the path contains a colon ( : )
The  srcds_run scrip sets the LD_LIBRARY_PATH to the path of it self.

LD_LIBRARY_PATH uses colons to seperate multiple pathes.

This Line from the srcds_run
``LD_LIBRARY_PATH=/var/www/html/_SERVERS/accounts/test/5.135.83.95:27016/740/bin:/ var/www/html/_SERVERS/accounts/test/5.135.83.95:27016/740:/var/www/html/_SERVERS /accounts/test/5.135.83.95:27016/740/bin:``

resolves to:
- /var/www/html/_SERVERS/accounts/test/5.135.83.95
- 27016/740/bin
- /var/www/html/_SERVERS/accounts/test/5.135.83.95
- 27016/740
- /var/www/html/_SERVERS/accounts/test/5.135.83.95
- 27016/740/bin

while it should be:
- /var/www/html/_SERVERS/accounts/test/5.135.83.95:27016/740/bin
- /var/www/html/_SERVERS/accounts/test/5.135.83.95:27016/740
- /var/www/html/_SERVERS/accounts/test/5.135.83.95:27016/740/bin

This problem is known and already in fixing. But unfortunately @devryan wasn't active the last few days.

**Comment by devryan** [comment]
This is fixed on the ip_port_fix branch of the master server:

https://github.com/devryan/GamePanelX-V3/tree/ip_port_fix

Please test it and let me know.

**Comment by matamata4** [comment]
@devryan After a clean install and a new git clone from the whole repo it's still not working.

Same issue, failed to open libtier0.so ...

"LD_LIBRARY_PATH=/var/www/html/_SERVERS/accounts/example/5.135.83.95:27020/740/bin:/var/www/html/_SERVERS/accounts/example/5.135.83.95:27020/740:/var/www/html/_SERVERS/accounts/example/5.135.83.95:27020/740/bin: Failed to open libtier0.so (libtier0.so: cannot open shared object file: No such file or directory) Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem Fri Nov 13 07:43:02 EST 2015: Server restart in 10 seconds"

**Comment by devryan** [comment]
What branches did you clone?  The fix is not in the master branch yet.

**Comment by zharding** [comment]
Hey Ryan, 

This doe not appear to have fixed the issue with current installs such as currently installed CS:GO servers. I attempted to start the server before reinstalling it, no luck. Still no luck after a reinstall. Same issue.

|| ERROR ||

LD_LIBRARY_PATH=/var/www/html/_SERVERS/accounts/marketing/216.144.246.227:27020/740/bin:/var/www/html/_SERVERS/accounts/marketing/216.144.246.227:27020/740:/var/www/html/_SERVERS/accounts/marketing/216.144.246.227:27020/740/bin: Failed to open libtier0.so (libtier0.so: cannot open shared object file: No such file or directory)

|| END ERROR ||

This was after applying the update you provided.

**Comment by siasur** [comment]
Are you sure that you are testing the correct branch(es)?

If you are just using ``GamePanel X`` you need the branch named "*ip_port_fix*".
If you are using ``GamePanel X Remote`` in addition you'll still need the "*ip_port_fix*" from ``GamePanel X`` and from the ``GamePanel X Remote`` you'll need the "*dev*" branch

**Comment by zharding** [comment]
Hey there, 

I have updated both. Same error.

**Comment by zharding** [comment]
Alrighty, 

Implemented the correct branch. Now I am getting weird start issues. So, I uninstalled the cs:go instance and reinstalled it. However, it is still displayed as offline. The console out appears to be running. I cannot connect to it, so I am sure there is something wonky somewhere.

**Comment by zharding** [comment]
Ok, it was a port issue. It did not like using something other than 2015.

**Comment by siasur** [comment]
Could you please check if the port is already bound by another service?

**Comment by devryan** [comment]
This has been fixed and merged into the master branch of both master and remote.

https://github.com/devryan/GamePanelX-V3/commit/29554eb7ed86c81e7fb4a919d4f37ebf5b39c27f

**Comment by devryan** [comment]
If you run the new code over from 3.0.11 to 3.0.12 make sure to visit your gpx.com/gpx/install to have it update your install.  Same for Remote upgrade, make sure to run update.sh.
