### ISSUE TITLE
php7 / mysqli support

### ISSUE THREAD

**Issue by vini0404** [devryan/GamePanelX-V3#172]
I get this error. I am using php 7.0 with mysqli on ubuntu.
Error: You do not have MySQL support (mysql_connect) built into PHP! Rebuild your PHP install with MySQL support and try again.

related to:
https://github.com/devryan/GamePanelX-V3/issues/155
will this ever getting fixed?

**Comment by will2therich** [comment]
Hi @vini0404 
Dont mean to self-advertise or anything (I can remove if you wish)
See my fork here that currently works on PHP 7.0 Let me know if you encounter any issues
https://github.com/will2therich/FlareServers-GamePanel

Ta,
Will

**Comment by devryan** [comment]
@will2therich I just opened an issue in your project, looks great.  If there are any feature-complete items I can merge them into the main GamePanelX codebase if they prove stable

**Comment by ghost** [comment]
This is an important error, because the app is designed under MYSQL and not MySQLi, need to start development to MySQLi

**Comment by ghost** [comment]
Im developing MySQLi Version, merge with my branch.

**Comment by will2therich** [comment]
Hi @devryan 
In regards to feature-complete items, so far PHP 7.0 support seems to be proving stable however will let you know how it continues to roll, I have integrated a system that blocks login after 5 attempts, maintenance mode functionality and sub user support(more work to do) currently had no issues with any however they need further testing.

Thanks,
Will

**Comment by will2therich** [comment]
Oh and one more thing I have also implemented SHA-256 encryption with personal and sitewide salt keys

**Comment by miloncse** [comment]
@will2therich i downloaded your version still getting same error.
php version  7.0.15

**Comment by will2therich** [comment]
@miloncse 
My bad the installer was still looking for mysql_connect and no mysqli_connect!
Sorted in the latest change
